### ISSUE TITLE
mdev specific nvidia profile overrides

### ISSUE THREAD

**Issue by tristan-k** [mbilker/vgpu_unlock-rs#12]
In PoIIoLocos [vGPU Proxmox guide](https://gitlab.com/polloloco/vgpu-proxmox#vgpu-overrides) there is chapter about the possibility to override certain VgpuConfig options. Is it possible to override the option `[profile.nvidia-XXX]` for specific VMs with `[mdev.00000000-0000-0000-0000-000000000XXX]`? Or is this a global variable which can’t be defined for specific VMs? For example I want to use `[profile.nvidia-47]`for `[mdev.00000000-0000-0000-0000-000000000100]` and  `[profile.nvidia-49]`for `[mdev.00000000-0000-0000-0000-000000000102]`. I don't want use the VMs at the same time because I do unterstand that it's not possible to mix and match profiles. Currently if I want to use a linux guest I will have to use a nvidia b profile because the performance of nvidia q profiles is utterly terrible. This conflicts with the nvidia q profile which I want to use for a windows guest. At line 146 of [lib.rs](https://github.com/mbilker/vgpu_unlock-rs/blob/master/src/lib.rs#L146=) I can see that there are options like `gpu_type` and `vgpu_type`. What are these for?

**Comment by alx696** [comment]
Seems just resolution settings wroks:

```
[profile.nvidia-257]
num_displays = 1
display_width = 1920
display_height = 1080
max_pixels = 2073600
```

I want limit frame rate to 60, but `frl_enabled = 1` not works.

Additional, do not set `framebuffer`! Otherwise, there will be random errors:
* `failed to read device config space: Bad address`
* `failed to get region 0 info: Input/output error`
> Try it a few times, it may go wrong and it will disappear.

**Comment by mbilker** [comment]
> At line 146 of [lib.rs](https://github.com/mbilker/vgpu_unlock-rs/blob/master/src/lib.rs#L146=) I can see that there are options like `gpu_type` and `vgpu_type`. What are these for?

They come straight from `/usr/share/nvidia/vgpu/vgpuConfig.xml`. `gpu_type` is the vGPU type ID. `vgpu_type` is the class (e.g. Quadro, NVS, Compute).

**Comment by mbilker** [comment]
> Additional, do not set `framebuffer`!

You can set `framebuffer`, but you have to make sure your card has enough VRAM free to support the allocation and that it has it in a single memory pool (i.e. not using a GTX 970 with its 3.5 GB and 0.5 GB memory pool split). I usually go off the `framebuffer` value for another profile in `vgpuConfig.xml`.

**Comment by mbilker** [comment]
As for the frame-rate limiter, multiple things can affect that.

**Comment by mbilker** [comment]
For setting a frame-rate limit, use `frl_config`. Additionally, it seems that setting the `vgpu_type` to `Quadro` requires certain hardware level features that are not available on GeForce cards. For full OpenGL performance, you can either use the older 450 driver release series or set `vgpu_type` to `NVS`.
