### ISSUE TITLE
Changing the name of the graphics card does not take effect?

### ISSUE THREAD

**Issue by wnark** [mbilker/vgpu_unlock-rs#13]
Similar to this, I changed the graphics card to RTX8000, but it still shows RTX6000 on Windows
```
[profile.nvidia-435]
card_name = "GRID RTX8000"
vgpu_type = "NVS"
pci_id = 0x1e301437
pci_device_id = 0x1e30
```
![image](https://user-images.githubusercontent.com/24355466/184052584-81a0b480-ce53-4db0-bbb9-5c95387af737.png)

**Comment by wnark** [comment]
![image](https://user-images.githubusercontent.com/24355466/184053602-3eeaae96-49a7-46bc-970f-bbfda03c33d6.png)
The graphics card model can be modified by modifying the hardware ID.

**Comment by mbilker** [comment]
Seems you figured out the issue? The card name as it appears in Device Manager is derived from the PCI IDs.
