### ISSUE TITLE
The card_name parameter is invalid, the virtual graphics card name will still be displayed

### ISSUE THREAD

**Issue by wnark** [mbilker/vgpu_unlock-rs#14]
I found that using the card_name parameter is invalid, and using GPU-Z can still display: GRID RTX6000-1B in: WDDM, opengl, and cuda, even if it has been replaced. This ID can be found in the registry
![image](https://user-images.githubusercontent.com/24355466/184568737-0a52d735-a6c4-4ea8-9240-46b035011dcb.png)
![image](https://user-images.githubusercontent.com/24355466/184568763-bc2c539c-8611-4dad-a2d9-e6a6d0466460.png)
![image](https://user-images.githubusercontent.com/24355466/184568782-9cbb9e2a-b631-4ade-8916-4baf8106eba9.png)
![image](https://user-images.githubusercontent.com/24355466/184568817-0084fb77-6411-423c-99e2-17d87c5f3540.png)

**Comment by mbilker** [comment]
There are multiple places where the card name is derived. The name that shows up in Device Manager is derived from the PCI IDs. The one that shows up in NVIDIA Control Panel (and other NVAPI functions) seems to be derived from the binary blob that the RM API pulls down into `nvidia-vgpu-mgr`.

**Comment by mbilker** [comment]
I added the ability to override the display name that shows up in NVIDIA Control Panel and via NVAPI to the latest version. Let me know if this does not satisfy your use-case.

**Comment by wnark** [comment]
Thanks, I'll check it 

> I added the ability to override the display name that shows up in NVIDIA Control Panel and via NVAPI to the latest version. Let me know if this does not satisfy your use-case.
