### ISSUE TITLE
unable to compile --noob issue

### ISSUE THREAD

**Issue by arcnet01** [mbilker/vgpu_unlock-rs#17]
Hi 

I am working my way through some vgpu tutorial.. 

proxmox 7.2 fresh install 
this tutorial: https://wvthoog.nl/proxmox-7-vgpu-v2/

when i run cargo build --release it will error out with the following:

error[E0658]: use of unstable library feature 'assoc_char_funcs': recently added
  --> src/format.rs:77:21
   |
77 |         for item in char::decode_utf16(self.0.iter().copied().take_while(|&ch| ch != 0)) {
   |                     ^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71763 <https://github.com/rust-lang/rust/issues/71763> for more information

error[E0658]: use of unstable library feature 'assoc_char_consts': recently added
  --> src/format.rs:78:41
   |
78 |             f.write_char(item.unwrap_or(char::REPLACEMENT_CHARACTER))?;
   |                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71763 <https://github.com/rust-lang/rust/issues/71763> for more information

error: aborting due to 2 previous errors

i have no idea how to get past this..  

Halp plz

**Comment by mbilker** [comment]
The compiler is complaining about some language features used that were unstable in the version of Rust installed on your system. However, I looked at the tracking issue and this was stabilized in Rust 1.52.0 but they were exposed on a different module in the older Rust language version included in Debian Bullseye, which is what Proxmox 7 is based on.

**Comment by arcnet01** [comment]
Thanks much. 

worked no issues
