### ISSUE TITLE
vGPU License 

### ISSUE THREAD

**Issue by srkaviani** [mbilker/vgpu_unlock-rs#18]
Hi.
I have many questions about NVIDIA vGPU Licensing.
1. Does this still require a nvidia vGPU License ?
2. I just got a 90-day free license and unlocked my vGPU functionality of my consumer grades GPU cards and I used this vGPUs in my Proxmox VMs.  Whats happen when that period (90 days) expires? 
Please Help me. Thanks.

**Comment by alx696** [comment]
Customer card like GTX 10.., RTX 20.. with plain driver do not need vGPU License. Grid driver need vGPU License.

**Comment by mbilker** [comment]
vGPU unlocking does not bypass the need for licensing when using the GRID guest driver.
