### ISSUE TITLE
CUDA in win/linux guest not available when device override used

### ISSUE THREAD

**Issue by rliwoch** [mbilker/vgpu_unlock-rs#21]
It's a rather curious case that affects CUDA capabilities when there's a device name override. I've got a few Teslas, M40, M40 24G, P100, and P4 and they all seem to exhibit the same issue.

For the windows guest - the acceleration works fine, taking the physical P100 as an example, I can spoof it as Quadro GP100 and the 3d rendering works ok, but CUDA doesn't 

For Linux guests (edit: same observed with Windows), as soon as the card device id and the subsystem id get overridden the CUDA capabilities are lost. 
Without the override, everything works fine, including CUDA. Seeing that `nvidia-smi` doesn't report an overridden GPU name (taking it directly from the mdev profile name?) - but `lspci` does, I suspect that the driver has a `dafaq` moment and doesn't know whether it's a CUDA capable device or not. But that's just a guess.
Initially I thought it might have been caused by the ROM BAR region being set to only 256M but that's not the case here. Without the override it still shows 256M, so BAR has to be handled somehow differently with vGPU.

The host happily reports the GPU is in C+G mode, indicating both Compute and GFX should be available, so there's something in the device id override that is making CUDA unavailable.

Host smi:
 
![m40smi](https://user-images.githubusercontent.com/26857299/198143875-531e6a5e-603d-483d-bf02-b44fbd38b682.png)

another host smi:

![p100smi](https://user-images.githubusercontent.com/26857299/198143903-b568fadf-3b80-4a34-8b42-0047d850c5cc.png)

guest SMI (with override active):

![guest](https://user-images.githubusercontent.com/26857299/198144128-3286dcd5-c35e-43cc-baf9-0bd23a9346da.png)

CUDA test with an override:
```
rliwoch@ubuntu-vpu-test:~$ docker run --rm --gpus all nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
[Vector addition of 50000 elements]
Failed to allocate device vector A (error code all CUDA-capable devices are busy or unavailable)!
```

Windows CUDA test with an override:
 
![cuda-win](https://user-images.githubusercontent.com/26857299/198144372-eb98ac5f-cf94-49e3-878b-b7e8410f3699.png)

Linux guest, CUDA without override:
```
rliwoch@ubuntu-vgpu-test:~$ docker run --rm --gpus all nvcr.io/nvidia/k8s/cuda-sample:vectoradd-cuda10.2
[Vector addition of 50000 elements]
Copy input data from the host memory to the CUDA device
CUDA kernel launch with 196 blocks of 256 threads
Copy output data from the CUDA device to the host memory
Test PASSED
Done

```

I'm posting it as a rather curious case, as I said in the beginning. 
I'm not sure if the override is needed in this for Linux Guest and CUDA, it happily took a normal driver (not a GRID one) - so there doesn't seem to be licensing requirements there. Having said that I don't want to start using it and find out that the performance of CUDA is crippled after some time (read somewhere that it can go into the limp mode after a while?) 

Any ideas as to why with an override the device suddenly stops accepting CUDA API calls?

for competness:

```
[profile.nvidia-86]
num_displays = 1
cuda_enabled = 1
frl_enabled = 0     
#Quadro GP100
#pci_device_id = 0x15F0
#pci_id = 0x15F011C3

#Windows box
[mdev.00000000-0000-0000-0000-000000000103]
pci_device_id = 0x15F0
pci_id = 0x15F011C3

#Linux box
[mdev.00000000-0000-0000-0000-000000000102]

```

**Comment by rliwoch** [comment]
BTW. 
`cuda_enabled` seems to be doing it's job when the device id is not spoofed.  Taking M40 24G as an example, that gets spoofed on the mdev level as a M60 - NVIDIA in their docs says only the 8Q profile is capable of CUDA:
![nvidia-wisdom](https://user-images.githubusercontent.com/26857299/198146203-17ea3868-4910-4dba-aaf9-c53d407a7e9b.png)

but with the `cuda_enabled` flag I was able to happily run CUDA apps on the 2Q profile (providing there's no device spoofing as decribed above).

Also, it doesn't matter where it's spoofed - the same behaviour when I spoof the device using your config.toml or override the device id on the KVM level.

**Comment by mbilker** [comment]
CUDA is not supported when spoofing the PCI device ID. So far, it only works with the GRID guest driver.

**Comment by rliwoch** [comment]
Did you ever investigate why is that?
I haven't gone through the nvidia's open source kernel modules myself, you must have, so I'm just curious what is so specific about spoofing and cuda

**Comment by mbilker** [comment]
There is some code path done with the GRID guest driver that does not happen when doing PCI-e ID spoofing for some reason.
