### ISSUE TITLE
Unable to override with two mdev profiles within one VM

### ISSUE THREAD

**Issue by nyacat** [mbilker/vgpu_unlock-rs#24]
OS: Proxmox 7.3
Kernel: 5.15.74-1-pve
Host Driver: 525.60.12
Guest Driver: 525.60.13
Hardware: RTX 2060 12G * 2

Host Config:
```
[mdev.00000000-0000-0000-0000-000000000102]
num_displays = 1
display_width = 1920
display_height = 1080
max_pixels = 2073600
cuda_enabled = 1
frl_enabled = 0
framebuffer = 0x162000000

[mdev.00000001-0000-0000-0000-000000000102]
num_displays = 1
display_width = 1920
display_height = 1080
max_pixels = 2073600
cuda_enabled = 1
frl_enabled = 0
framebuffer = 0x162000000
```

VM Config
```
hostpci0: 0000:82:00.0,mdev=nvidia-259,pcie=1
hostpci1: 0000:01:00.0,mdev=nvidia-259,pcie=1
```

PVE vm Start
```
kvm: -device vfio-pci,sysfsdev=/sys/bus/mdev/devices/00000000-0000-0000-0000-000000000102,id=hostpci0,bus=ich9-pcie-port-1,addr=0x0: warning: vfio 00000000-0000-0000-0000-000000000102: Could not enable error recovery for the device
kvm: -device vfio-pci,sysfsdev=/sys/bus/mdev/devices/00000001-0000-0000-0000-000000000102,id=hostpci1,bus=ich9-pcie-port-2,addr=0x0: warning: vfio 00000001-0000-0000-0000-000000000102: Could not enable error recovery for the device
TASK OK
```

Host journalctl nvidia-vgpu-mgr.service
[pastebin](https://pastebin.com/raw/rp0e9A95)

Problem:
When two vGPUs are added to a virtual machine, the mdev override does not work properly, but if override with a profile it works fine.

**Comment by mbilker** [comment]
From the system log, I see that the second start call is not recognized as a start call so it might be using a different command code so it likely needs additional support in `vgpu_unlock-rs`.

**Comment by mbilker** [comment]
This should be fixed with recent commits and especially https://github.com/mbilker/vgpu_unlock-rs/commit/ba66a6c6eeb16eb8e2d2ec368d6605b974070d4b
