### ISSUE TITLE
have anyone gotten rtx 30 series card to work yet?

### ISSUE THREAD

**Issue by poohzaza166** [mbilker/vgpu_unlock-rs#25]

**Comment by mbilker** [comment]
See #16

**Comment by mbilker** [comment]
> While Ampere is listed in the source code, the guest driver fails to load on all consumer cards. If you would like to investigate as to why the guest driver does not load, feel free to do so. There are many people that would like to use a 3090 for GPU virtualization outside of Hyper-V's GPU Partitioning.
