### ISSUE TITLE
[PROMOX][OVERRIDE]mdev uuid to vmid fail

### ISSUE THREAD

**Issue by disfoundme** [mbilker/vgpu_unlock-rs#34]
It seems that the function uuid_to_vmid [in src/utils](https://github.com/mbilker/vgpu_unlock-rs/blob/master/src/utils.rs#L38)  has some problems.

    // Ensure that the first parts of the uuid are only 0
    if uuid.0 != 0 || uuid.1 != 0 || uuid.2 != 0 || uuid.3[0] != 0 || uuid.3[1] != 0 {
        return None;
    }

The first block  should be the vm PCIE number.. 
Refer. https://forum.proxmox.com/threads/automatically-assign-uuid-to-a-vgpu-instance.98994/post-427480

**Comment by mbilker** [comment]
Thank you for the report!
