### ISSUE TITLE
Multi gpu/vgpu to a single vm?

### ISSUE THREAD

**Issue by AncientMystic** [mbilker/vgpu_unlock-rs#38]
I am trying to get multiple gpus/vgpus on a single VM but it just doesn't seem to work. 

Is it possible in any way? 

The best i can get half working is adding the P4 via vGPU profile then passing the 1060 through, but then the drivers are incompatible. if i spoof the device ID to a quadro or something else, same result. So it seems that it has to be via vGPU profiles. 

The output of "journalctl --no-pager -b 0 -u nvidia-vgpu-mgr.service" says this:
error: vmiop_log: (0x1): init_device_instance failed for inst 1 with error 1 (multiple vGPUs in a VM not supported)

Which is fairly self explanatory.... 

vGPU/GPU or vGPU/vGPU combos do not work.

I also have a intel arc A310 in the same vm and the intel Arc+vGPU profile works fine. It's just nvidia vgpu+gpu that i cannot get working. 

But i have seen on threads on nvidia forums/other places, such as discussing vSphere, saying you can have up to 4 vGPUs in a single VM, if you have multiple physical cards and you only use them with the one VM.

I am interested in getting this working for GPGPU/CUDA tasks such as LLMs, etc. i was even considering getting another better card to replace the 1060 or another P4 but i need multiple vGPU or vGPU+GPU to work first or it is a waste of time to get more cards i cannot use. 

I am also wondering, can i set the unlock to appear as a p4 instead of a p40?

**Comment by mbilker** [comment]
Multi-vGPU support was added with later cards.

https://www.nvidia.com/en-us/design-visualization/solutions/multi-virtual-gpus/

**Comment by mbilker** [comment]
As for changing the card to appear as a P4 instead of a P40, that can be done by changing the PCI IDs to the P4 at
https://github.com/DualCoder/vgpu_unlock/blob/f432ffc8b7ed245df8858e9b38000d3b8f0352f4/vgpu_unlock_hooks.c#L822
and this project at
https://github.com/mbilker/vgpu_unlock-rs/blob/ba66a6c6eeb16eb8e2d2ec368d6605b974070d4b/src/lib.rs#L369-L370

**Comment by AncientMystic** [comment]
Thank you for the information, I appreciate it. 

So multi-vgpu support isn't possible with pascal? 

Any ideas if that is a hardware limitation or simply a software limitation? 

Also if someone wanted this feature, for instance if i were to upgrade my GPUs is there hardware that both supports multi vGPU and compatible with vGPU unlock? 

I was thinking about upgrading to RTX 20 or 30 series (but I understand 30/40 isn't supported by unlock)

**Comment by alealexpro100** [comment]
Confirming that changing from `0x1b38` to `0x1bb3` (from Tesla P4) allows to use multi vGPU on one VM. Tested on two P104-100 with patched 535.216.01.
Note: profile names are other with new PCI ID.
