### ISSUE TITLE
ampere support

### ISSUE THREAD

**Issue by verna123456** [mbilker/vgpu_unlock-rs#39]
based on this post : 
https://www.techpowerup.com/312631/nvidia-bios-signature-lock-broken-vbios-modding-and-crossflash-enabled-by-groundbreaking-new-tools
is there any progress in supporting ampere architecture  GPUs?

**Comment by mbilker** [comment]
There is no progress as Ampere GPUs that officially support vGPU use SR-IOV. As far as I know at the time of writing this response, there is no current VBIOS tweak or hardware modification to enable SR-IOV capabilities on consumer Ampere and newer cards.
